---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jenkins-wordpress
subjects:
- kind: ServiceAccount
  name: qsrjenkins
  namespace: qsrautowordpress  # Replace <your-namespace> with the namespace where the service account is created (e.g., jenkins)
roleRef:
  kind: ClusterRole
  name: jenkins
  apiGroup: rbac.authorization.k8s.io
